EPA_FACTORS = [
    {"activity": "Steel production - basic oxygen furnace", "factor": 1.85, "unit": "kg CO2e/kg"},
    {"activity": "Electricity generation - grid average", "factor": 0.42, "unit": "kg CO2e/kWh"},
    {"activity": "Natural gas combustion - industrial", "factor": 2.02, "unit": "kg CO2e/m3"},
    {"activity": "Diesel fuel combustion - mobile sources", "factor": 2.68, "unit": "kg CO2e/L"},
    {"activity": "Gasoline fuel combustion - mobile sources", "factor": 2.31, "unit": "kg CO2e/L"},
    {"activity": "Concrete production - ready-mixed", "factor": 0.13, "unit": "kg CO2e/kg"},
    {"activity": "Aluminum production - primary", "factor": 8.14, "unit": "kg CO2e/kg"},
    {"activity": "Paper production - virgin fiber", "factor": 1.09, "unit": "kg CO2e/kg"},
    {"activity": "Plastic production - general polymers", "factor": 2.53, "unit": "kg CO2e/kg"},
    {"activity": "Road freight transport - heavy truck", "factor": 0.21, "unit": "kg CO2e/t-km"},
    {"activity": "Air travel - short haul", "factor": 0.15, "unit": "kg CO2e/passenger-km"},
    {"activity": "Rail freight transport", "factor": 0.03, "unit": "kg CO2e/t-km"},
    {"activity": "Water consumption - municipal supply", "factor": 0.34, "unit": "kg CO2e/m3"},
    {"activity": "Waste to landfill - mixed municipal", "factor": 0.58, "unit": "kg CO2e/kg"},
    {"activity": "Copper production - primary", "factor": 3.83, "unit": "kg CO2e/kg"},
    {"activity": "Glass production - container glass", "factor": 0.85, "unit": "kg CO2e/kg"},
    {"activity": "Cotton textile production", "factor": 5.89, "unit": "kg CO2e/kg"},
    {"activity": "District heating - natural gas boiler", "factor": 0.18, "unit": "kg CO2e/kWh"},
    {"activity": "Refrigerant use - HFC leakage", "factor": 1430.0, "unit": "kg CO2e/kg"},
    {"activity": "General industrial activity", "factor": 1.5, "unit": "kg CO2e/unit"},
    {"activity": "Reported GHG emissions - direct facility calculation", "factor": 1.0, "unit": "kg CO2e/kg CO2e"},
    {"activity": "Direct reported emissions - Metric Tons CO2e", "factor": 1000.0, "unit": "kg CO2e/MT CO2e"},
]
